# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1160, 670)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/icon.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-image: url(:/newPrefix/try.png);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setBold(True)
        font.setWeight(75)
        self.centralwidget.setFont(font)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 1141, 967))
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"border-color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 254, 206);")
        self.tabWidget.setObjectName("tabWidget")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.label_21 = QtWidgets.QLabel(self.tab_5)
        self.label_21.setGeometry(QtCore.QRect(0, 0, 1141, 611))
        self.label_21.setText("")
        self.label_21.setPixmap(QtGui.QPixmap("images/bg_img.jpg"))
        self.label_21.setScaledContents(True)
        self.label_21.setObjectName("label_21")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/marhaba.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_5, icon1, "")
        self.tab = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.tab.setFont(font)
        self.tab.setObjectName("tab")
        self.textEdit_mot1 = QtWidgets.QTextEdit(self.tab)
        self.textEdit_mot1.setGeometry(QtCore.QRect(630, 10, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Traditional Arabic")
        font.setPointSize(14)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.textEdit_mot1.setFont(font)
        self.textEdit_mot1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textEdit_mot1.setObjectName("textEdit_mot1")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(800, 10, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Traditional Arabic")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(1130, 720, 81, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(600, 430, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Traditional Arabic")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(1000, 430, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Traditional Arabic")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(990, 250, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Traditional Arabic")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(600, 250, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Traditional Arabic")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.tab)
        self.label_10.setGeometry(QtCore.QRect(590, 50, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Traditional Arabic")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.tab)
        self.label_11.setGeometry(QtCore.QRect(250, 50, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Traditional Arabic")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.tab)
        self.label_12.setGeometry(QtCore.QRect(240, 250, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Traditional Arabic")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.button_visualisation1 = QtWidgets.QPushButton(self.tab)
        self.button_visualisation1.setGeometry(QtCore.QRect(60, 10, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Traditional Arabic")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.button_visualisation1.setFont(font)
        self.button_visualisation1.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.button_visualisation1.setStyleSheet("background-color: rgb(255, 189, 158);\n"
"background-color: rgb(255, 255, 127);")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("images/add.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_visualisation1.setIcon(icon2)
        self.button_visualisation1.setObjectName("button_visualisation1")
        self.pushbutton = QtWidgets.QPushButton(self.tab)
        self.pushbutton.setGeometry(QtCore.QRect(530, 10, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Traditional Arabic")
        font.setPointSize(16)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.pushbutton.setFont(font)
        self.pushbutton.setStyleSheet("background-color: rgb(255, 189, 158);\n"
"background-color: rgb(255, 255, 127);")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("images/magnifying-glass-303408_960_720.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushbutton.setIcon(icon3)
        self.pushbutton.setObjectName("pushbutton")
        self.textEdit = QtWidgets.QTextEdit(self.tab)
        self.textEdit.setGeometry(QtCore.QRect(790, 80, 321, 141))
        font = QtGui.QFont()
        font.setFamily("Traditional Arabic")
        font.setPointSize(14)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.textEdit.setFont(font)
        self.textEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textEdit.setObjectName("textEdit")
        self.label_20 = QtWidgets.QLabel(self.tab)
        self.label_20.setGeometry(QtCore.QRect(960, 50, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Traditional Arabic")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.textEditAsr3 = QtWidgets.QTextEdit(self.tab)
        self.textEditAsr3.setGeometry(QtCore.QRect(30, 80, 321, 141))
        font = QtGui.QFont()
        font.setFamily("Traditional Arabic")
        font.setPointSize(14)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.textEditAsr3.setFont(font)
        self.textEditAsr3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textEditAsr3.setObjectName("textEditAsr3")
        self.textEditAsr5 = QtWidgets.QTextEdit(self.tab)
        self.textEditAsr5.setGeometry(QtCore.QRect(410, 460, 321, 141))
        font = QtGui.QFont()
        font.setFamily("Traditional Arabic")
        font.setPointSize(14)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.textEditAsr5.setFont(font)
        self.textEditAsr5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textEditAsr5.setObjectName("textEditAsr5")
        self.textEditAsr2_2 = QtWidgets.QTextEdit(self.tab)
        self.textEditAsr2_2.setGeometry(QtCore.QRect(410, 280, 321, 141))
        font = QtGui.QFont()
        font.setFamily("Traditional Arabic")
        font.setPointSize(14)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.textEditAsr2_2.setFont(font)
        self.textEditAsr2_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textEditAsr2_2.setObjectName("textEditAsr2_2")
        self.textEditAsr6 = QtWidgets.QTextEdit(self.tab)
        self.textEditAsr6.setGeometry(QtCore.QRect(30, 280, 321, 141))
        font = QtGui.QFont()
        font.setFamily("Traditional Arabic")
        font.setPointSize(14)
        self.textEditAsr6.setFont(font)
        self.textEditAsr6.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textEditAsr6.setObjectName("textEditAsr6")
        self.textEditAsr7 = QtWidgets.QTextEdit(self.tab)
        self.textEditAsr7.setGeometry(QtCore.QRect(790, 460, 321, 141))
        font = QtGui.QFont()
        font.setFamily("Traditional Arabic")
        font.setPointSize(14)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.textEditAsr7.setFont(font)
        self.textEditAsr7.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textEditAsr7.setObjectName("textEditAsr7")
        self.textEditAsr4 = QtWidgets.QTextEdit(self.tab)
        self.textEditAsr4.setGeometry(QtCore.QRect(790, 280, 321, 141))
        font = QtGui.QFont()
        font.setFamily("Traditional Arabic")
        font.setPointSize(14)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.textEditAsr4.setFont(font)
        self.textEditAsr4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textEditAsr4.setObjectName("textEditAsr4")
        self.textEditAsr1 = QtWidgets.QTextEdit(self.tab)
        self.textEditAsr1.setGeometry(QtCore.QRect(400, 80, 321, 141))
        font = QtGui.QFont()
        font.setFamily("Traditional Arabic")
        font.setPointSize(14)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.textEditAsr1.setFont(font)
        self.textEditAsr1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textEditAsr1.setObjectName("textEditAsr1")
        self.textEdit_15 = QtWidgets.QTextEdit(self.tab)
        self.textEdit_15.setGeometry(QtCore.QRect(250, 10, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Traditional Arabic")
        font.setPointSize(14)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.textEdit_15.setFont(font)
        self.textEdit_15.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textEdit_15.setObjectName("textEdit_15")
        self.label_19 = QtWidgets.QLabel(self.tab)
        self.label_19.setGeometry(QtCore.QRect(370, 10, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Traditional Arabic")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.button_visualisation1_2 = QtWidgets.QPushButton(self.tab)
        self.button_visualisation1_2.setGeometry(QtCore.QRect(130, 440, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Traditional Arabic")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.button_visualisation1_2.setFont(font)
        self.button_visualisation1_2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.button_visualisation1_2.setStyleSheet("background-color: rgb(255, 189, 158);\n"
"background-color: rgb(255, 255, 127);")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("images/show.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_visualisation1_2.setIcon(icon4)
        self.button_visualisation1_2.setObjectName("button_visualisation1_2")
        self.textEditAsr6_2 = QtWidgets.QTextEdit(self.tab)
        self.textEditAsr6_2.setGeometry(QtCore.QRect(30, 480, 321, 121))
        font = QtGui.QFont()
        font.setFamily("Traditional Arabic")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.textEditAsr6_2.setFont(font)
        self.textEditAsr6_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textEditAsr6_2.setObjectName("textEditAsr6_2")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("images/auto.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab, icon5, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.textEdit_2 = QtWidgets.QTextEdit(self.tab_3)
        self.textEdit_2.setGeometry(QtCore.QRect(490, 20, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Traditional Arabic")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.textEdit_2.setFont(font)
        self.textEdit_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textEdit_2.setObjectName("textEdit_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_3.setGeometry(QtCore.QRect(80, 20, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Traditional Arabic")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("background-color: rgb(255, 255, 127);")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("images/add def.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon6)
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_3 = QtWidgets.QLabel(self.tab_3)
        self.label_3.setGeometry(QtCore.QRect(1050, 80, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Traditional Arabic")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.tab_3)
        self.label_4.setGeometry(QtCore.QRect(970, 210, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Traditional Arabic")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.textEdit_3 = QtWidgets.QTextEdit(self.tab_3)
        self.textEdit_3.setGeometry(QtCore.QRect(623, 110, 501, 71))
        font = QtGui.QFont()
        font.setFamily("Traditional Arabic")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.textEdit_3.setFont(font)
        self.textEdit_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textEdit_3.setObjectName("textEdit_3")
        self.textEdit_4 = QtWidgets.QTextEdit(self.tab_3)
        self.textEdit_4.setGeometry(QtCore.QRect(620, 240, 511, 71))
        font = QtGui.QFont()
        font.setFamily("Traditional Arabic")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.textEdit_4.setFont(font)
        self.textEdit_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textEdit_4.setObjectName("textEdit_4")
        self.textEdit_5 = QtWidgets.QTextEdit(self.tab_3)
        self.textEdit_5.setGeometry(QtCore.QRect(620, 370, 511, 71))
        font = QtGui.QFont()
        font.setFamily("Traditional Arabic")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.textEdit_5.setFont(font)
        self.textEdit_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textEdit_5.setObjectName("textEdit_5")
        self.label_13 = QtWidgets.QLabel(self.tab_3)
        self.label_13.setGeometry(QtCore.QRect(970, 340, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Traditional Arabic")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.textEdit_6 = QtWidgets.QTextEdit(self.tab_3)
        self.textEdit_6.setGeometry(QtCore.QRect(620, 480, 511, 71))
        font = QtGui.QFont()
        font.setFamily("Traditional Arabic")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.textEdit_6.setFont(font)
        self.textEdit_6.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textEdit_6.setObjectName("textEdit_6")
        self.label_14 = QtWidgets.QLabel(self.tab_3)
        self.label_14.setGeometry(QtCore.QRect(970, 450, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Traditional Arabic")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.tab_3)
        self.label_15.setGeometry(QtCore.QRect(370, 80, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Traditional Arabic")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.textEdit_7 = QtWidgets.QTextEdit(self.tab_3)
        self.textEdit_7.setGeometry(QtCore.QRect(20, 110, 511, 71))
        font = QtGui.QFont()
        font.setFamily("Traditional Arabic")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.textEdit_7.setFont(font)
        self.textEdit_7.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textEdit_7.setObjectName("textEdit_7")
        self.label_16 = QtWidgets.QLabel(self.tab_3)
        self.label_16.setGeometry(QtCore.QRect(370, 210, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Traditional Arabic")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.textEdit_8 = QtWidgets.QTextEdit(self.tab_3)
        self.textEdit_8.setGeometry(QtCore.QRect(20, 240, 511, 71))
        font = QtGui.QFont()
        font.setFamily("Traditional Arabic")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.textEdit_8.setFont(font)
        self.textEdit_8.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textEdit_8.setObjectName("textEdit_8")
        self.textEdit_9 = QtWidgets.QTextEdit(self.tab_3)
        self.textEdit_9.setGeometry(QtCore.QRect(20, 370, 511, 71))
        font = QtGui.QFont()
        font.setFamily("Traditional Arabic")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.textEdit_9.setFont(font)
        self.textEdit_9.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textEdit_9.setObjectName("textEdit_9")
        self.textEdit_10 = QtWidgets.QTextEdit(self.tab_3)
        self.textEdit_10.setGeometry(QtCore.QRect(20, 480, 511, 71))
        font = QtGui.QFont()
        font.setFamily("Traditional Arabic")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.textEdit_10.setFont(font)
        self.textEdit_10.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textEdit_10.setObjectName("textEdit_10")
        self.label_17 = QtWidgets.QLabel(self.tab_3)
        self.label_17.setGeometry(QtCore.QRect(370, 340, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Traditional Arabic")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.tab_3)
        self.label_18.setGeometry(QtCore.QRect(370, 450, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Traditional Arabic")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.pushButton4 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton4.setGeometry(QtCore.QRect(560, 130, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Traditional Arabic")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton4.setFont(font)
        self.pushButton4.setStyleSheet("background-color: rgb(255, 255, 127);")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("images/plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton4.setIcon(icon7)
        self.pushButton4.setObjectName("pushButton4")
        self.label_34 = QtWidgets.QLabel(self.tab_3)
        self.label_34.setGeometry(QtCore.QRect(670, 20, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Traditional Arabic")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("images/man.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_3, icon8, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.comboBox = QtWidgets.QComboBox(self.tab_2)
        self.comboBox.setGeometry(QtCore.QRect(970, 60, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Traditional Arabic")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.tableWidget_Corpus = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget_Corpus.setGeometry(QtCore.QRect(460, 50, 471, 531))
        font = QtGui.QFont()
        font.setFamily("Traditional Arabic")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.tableWidget_Corpus.setFont(font)
        self.tableWidget_Corpus.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableWidget_Corpus.setObjectName("tableWidget_Corpus")
        self.tableWidget_Corpus.setColumnCount(1)
        self.tableWidget_Corpus.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tableWidget_Corpus.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Corpus.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tableWidget_Corpus.setItem(0, 0, item)
        self.textEdit_16 = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit_16.setGeometry(QtCore.QRect(10, 50, 411, 531))
        font = QtGui.QFont()
        font.setFamily("Traditional Arabic")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.textEdit_16.setFont(font)
        self.textEdit_16.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textEdit_16.setObjectName("textEdit_16")
        self.pushButton_show = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_show.setGeometry(QtCore.QRect(1000, 130, 101, 23))
        font = QtGui.QFont()
        font.setFamily("Traditional Arabic")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_show.setFont(font)
        self.pushButton_show.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.pushButton_show.setIcon(icon4)
        self.pushButton_show.setObjectName("pushButton_show")
        self.label_22 = QtWidgets.QLabel(self.tab_2)
        self.label_22.setGeometry(QtCore.QRect(320, 20, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Traditional Arabic")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("images/text.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_2, icon9, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.groupBox = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox.setGeometry(QtCore.QRect(10, 20, 471, 151))
        font = QtGui.QFont()
        font.setFamily("Traditional Arabic")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_2.setGeometry(QtCore.QRect(10, 50, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Traditional Arabic")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_3 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_3.setGeometry(QtCore.QRect(270, 50, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Traditional Arabic")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_3.setFont(font)
        self.comboBox_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_2.setGeometry(QtCore.QRect(110, 110, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Traditional Arabic")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: rgb(255, 255, 127);")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("images/compare2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon10)
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_23 = QtWidgets.QLabel(self.groupBox)
        self.label_23.setGeometry(QtCore.QRect(100, 23, 47, 20))
        font = QtGui.QFont()
        font.setFamily("Traditional Arabic")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.groupBox)
        self.label_24.setGeometry(QtCore.QRect(360, 23, 47, 20))
        font = QtGui.QFont()
        font.setFamily("Traditional Arabic")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.textEdit_22 = QtWidgets.QTextEdit(self.groupBox)
        self.textEdit_22.setGeometry(QtCore.QRect(200, 110, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Traditional Arabic")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.textEdit_22.setFont(font)
        self.textEdit_22.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textEdit_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.textEdit_22.setObjectName("textEdit_22")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 210, 471, 171))
        font = QtGui.QFont()
        font.setFamily("Traditional Arabic")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.comboBox_4 = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_4.setGeometry(QtCore.QRect(10, 30, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Traditional Arabic")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_4.setFont(font)
        self.comboBox_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.spinBox = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox.setGeometry(QtCore.QRect(60, 70, 42, 22))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.spinBox.setFont(font)
        self.spinBox.setReadOnly(False)
        self.spinBox.setMinimum(1)
        self.spinBox.setMaximum(100)
        self.spinBox.setObjectName("spinBox")
        self.label_25 = QtWidgets.QLabel(self.groupBox_2)
        self.label_25.setGeometry(QtCore.QRect(156, 30, 31, 20))
        font = QtGui.QFont()
        font.setFamily("Traditional Arabic")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.groupBox_2)
        self.label_26.setGeometry(QtCore.QRect(110, 70, 81, 20))
        font = QtGui.QFont()
        font.setFamily("Traditional Arabic")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_4.setGeometry(QtCore.QRect(50, 120, 151, 23))
        font = QtGui.QFont()
        font.setFamily("Traditional Arabic")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.pushButton_4.setIcon(icon4)
        self.pushButton_4.setObjectName("pushButton_4")
        self.textEdit_14 = QtWidgets.QTextEdit(self.groupBox_2)
        self.textEdit_14.setGeometry(QtCore.QRect(250, 30, 211, 131))
        font = QtGui.QFont()
        font.setFamily("Traditional Arabic")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.textEdit_14.setFont(font)
        self.textEdit_14.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textEdit_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.textEdit_14.setObjectName("textEdit_14")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_3.setGeometry(QtCore.QRect(650, 60, 481, 521))
        font = QtGui.QFont()
        font.setFamily("Traditional Arabic")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_5.setGeometry(QtCore.QRect(370, 30, 91, 23))
        font = QtGui.QFont()
        font.setFamily("Traditional Arabic")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.pushButton_5.setIcon(icon9)
        self.pushButton_5.setObjectName("pushButton_5")
        self.textEdit_13 = QtWidgets.QTextEdit(self.groupBox_3)
        self.textEdit_13.setGeometry(QtCore.QRect(70, 30, 291, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.textEdit_13.setFont(font)
        self.textEdit_13.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textEdit_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.textEdit_13.setObjectName("textEdit_13")
        self.label_27 = QtWidgets.QLabel(self.groupBox_3)
        self.label_27.setGeometry(QtCore.QRect(330, 110, 121, 20))
        font = QtGui.QFont()
        font.setFamily("Traditional Arabic")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.textEdit_17 = QtWidgets.QTextEdit(self.groupBox_3)
        self.textEdit_17.setGeometry(QtCore.QRect(250, 100, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Traditional Arabic")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.textEdit_17.setFont(font)
        self.textEdit_17.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textEdit_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.textEdit_17.setObjectName("textEdit_17")
        self.label_28 = QtWidgets.QLabel(self.groupBox_3)
        self.label_28.setGeometry(QtCore.QRect(310, 155, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Traditional Arabic")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_6.setGeometry(QtCore.QRect(40, 100, 171, 23))
        font = QtGui.QFont()
        font.setFamily("Traditional Arabic")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("background-color: rgb(255, 255, 127);")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("images/lngth.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_6.setIcon(icon11)
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_7.setGeometry(QtCore.QRect(50, 250, 131, 23))
        font = QtGui.QFont()
        font.setFamily("Traditional Arabic")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("background-color: rgb(255, 255, 127);")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("images/frequency_293698.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_7.setIcon(icon12)
        self.pushButton_7.setObjectName("pushButton_7")
        self.textEdit_18 = QtWidgets.QTextEdit(self.groupBox_3)
        self.textEdit_18.setGeometry(QtCore.QRect(200, 180, 261, 141))
        font = QtGui.QFont()
        font.setFamily("Traditional Arabic")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.textEdit_18.setFont(font)
        self.textEdit_18.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textEdit_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.textEdit_18.setObjectName("textEdit_18")
        self.label_31 = QtWidgets.QLabel(self.groupBox_3)
        self.label_31.setGeometry(QtCore.QRect(290, 349, 161, 21))
        font = QtGui.QFont()
        font.setFamily("Traditional Arabic")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.pushButton_9 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_9.setGeometry(QtCore.QRect(10, 440, 181, 23))
        font = QtGui.QFont()
        font.setFamily("Traditional Arabic")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.pushButton_9.setIcon(icon12)
        self.pushButton_9.setObjectName("pushButton_9")
        self.textEdit_21 = QtWidgets.QTextEdit(self.groupBox_3)
        self.textEdit_21.setGeometry(QtCore.QRect(200, 370, 261, 141))
        font = QtGui.QFont()
        font.setFamily("Traditional Arabic")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.textEdit_21.setFont(font)
        self.textEdit_21.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textEdit_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.textEdit_21.setObjectName("textEdit_21")
        self.spinBox_2 = QtWidgets.QSpinBox(self.groupBox_3)
        self.spinBox_2.setGeometry(QtCore.QRect(50, 210, 42, 22))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.spinBox_2.setFont(font)
        self.spinBox_2.setReadOnly(False)
        self.spinBox_2.setMinimum(1)
        self.spinBox_2.setMaximum(100)
        self.spinBox_2.setObjectName("spinBox_2")
        self.spinBox_3 = QtWidgets.QSpinBox(self.groupBox_3)
        self.spinBox_3.setGeometry(QtCore.QRect(50, 400, 42, 22))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.spinBox_3.setFont(font)
        self.spinBox_3.setReadOnly(False)
        self.spinBox_3.setMinimum(1)
        self.spinBox_3.setMaximum(100)
        self.spinBox_3.setObjectName("spinBox_3")
        self.label_32 = QtWidgets.QLabel(self.groupBox_3)
        self.label_32.setGeometry(QtCore.QRect(100, 210, 81, 20))
        font = QtGui.QFont()
        font.setFamily("Traditional Arabic")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.groupBox_3)
        self.label_33.setGeometry(QtCore.QRect(100, 400, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Traditional Arabic")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 430, 471, 171))
        font = QtGui.QFont()
        font.setFamily("Traditional Arabic")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.comboBox_5 = QtWidgets.QComboBox(self.groupBox_4)
        self.comboBox_5.setGeometry(QtCore.QRect(20, 30, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Traditional Arabic")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_5.setFont(font)
        self.comboBox_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.label_29 = QtWidgets.QLabel(self.groupBox_4)
        self.label_29.setGeometry(QtCore.QRect(160, 33, 47, 20))
        font = QtGui.QFont()
        font.setFamily("Traditional Arabic")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.groupBox_4)
        self.label_30.setGeometry(QtCore.QRect(390, 40, 51, 16))
        font = QtGui.QFont()
        font.setFamily("Traditional Arabic")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.pushButton_8 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_8.setGeometry(QtCore.QRect(120, 90, 81, 23))
        font = QtGui.QFont()
        font.setFamily("Traditional Arabic")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.pushButton_8.setIcon(icon12)
        self.pushButton_8.setObjectName("pushButton_8")
        self.textEdit_19 = QtWidgets.QTextEdit(self.groupBox_4)
        self.textEdit_19.setGeometry(QtCore.QRect(240, 90, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Traditional Arabic")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.textEdit_19.setFont(font)
        self.textEdit_19.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textEdit_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.textEdit_19.setObjectName("textEdit_19")
        self.textEdit_20 = QtWidgets.QTextEdit(self.groupBox_4)
        self.textEdit_20.setGeometry(QtCore.QRect(290, 30, 104, 31))
        font = QtGui.QFont()
        font.setFamily("Traditional Arabic")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.textEdit_20.setFont(font)
        self.textEdit_20.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textEdit_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.textEdit_20.setObjectName("textEdit_20")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("images/stats.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_4, icon13, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "القاموس التاريخي "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "مرحبا"))
        self.label.setText(_translate("MainWindow", "إختيار الكلمة"))
        self.label_5.setText(_translate("MainWindow", "العصر العباسي"))
        self.label_6.setText(_translate("MainWindow", "العصور الوسطى"))
        self.label_7.setText(_translate("MainWindow", "القرآن الكريم"))
        self.label_8.setText(_translate("MainWindow", "العصر العباسي"))
        self.label_9.setText(_translate("MainWindow", "العصر الإسلامي"))
        self.label_10.setText(_translate("MainWindow", "العصر الجاهلي"))
        self.label_11.setText(_translate("MainWindow", "العصر الاموي"))
        self.label_12.setText(_translate("MainWindow", "العصر الحديث"))
        self.button_visualisation1.setText(_translate("MainWindow", "تأكيد الإضافة"))
        self.pushbutton.setText(_translate("MainWindow", "بحث"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Traditional Arabic\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8.25pt;\"><br /></p></body></html>"))
        self.label_20.setText(_translate("MainWindow", "التعريف المقترح"))
        self.textEditAsr3.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Traditional Arabic\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8.25pt;\"><br /></p></body></html>"))
        self.textEditAsr5.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Traditional Arabic\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8.25pt;\"><br /></p></body></html>"))
        self.textEditAsr2_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Traditional Arabic\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8.25pt;\"><br /></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8.25pt;\"><br /></p></body></html>"))
        self.textEditAsr6.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Traditional Arabic\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8.25pt;\"><br /></p></body></html>"))
        self.textEditAsr7.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Traditional Arabic\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8.25pt;\"><br /></p></body></html>"))
        self.textEditAsr4.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Traditional Arabic\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8.25pt;\"><br /></p></body></html>"))
        self.textEditAsr1.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Traditional Arabic\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8.25pt;\"><br /></p></body></html>"))
        self.label_19.setText(_translate("MainWindow", "الوضعية"))
        self.button_visualisation1_2.setText(_translate("MainWindow", "إظهار الكلمات المضافة"))
        self.textEditAsr6_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Traditional Arabic\'; font-size:14pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400;\"><br /></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "الوضع التلقائي "))
        self.textEdit_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Traditional Arabic\'; font-size:14pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400;\"><br /></p></body></html>"))
        self.pushButton_3.setText(_translate("MainWindow", "إضافة التعريف"))
        self.label_3.setText(_translate("MainWindow", "تعريف"))
        self.label_4.setText(_translate("MainWindow", "مثال العصر الجاهلي  "))
        self.textEdit_3.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Traditional Arabic\'; font-size:14pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400;\"><br /></p></body></html>"))
        self.textEdit_4.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Traditional Arabic\'; font-size:14pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400;\"><br /></p></body></html>"))
        self.textEdit_5.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Traditional Arabic\'; font-size:14pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400;\"><br /></p></body></html>"))
        self.label_13.setText(_translate("MainWindow", "مثال العصر الإسلامي  "))
        self.textEdit_6.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Traditional Arabic\'; font-size:14pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400;\"><br /></p></body></html>"))
        self.label_14.setText(_translate("MainWindow", "مثال العصر الاموي  "))
        self.label_15.setText(_translate("MainWindow", "مثال العصر العباسي "))
        self.textEdit_7.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Traditional Arabic\'; font-size:14pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400;\"><br /></p></body></html>"))
        self.label_16.setText(_translate("MainWindow", "مثال العصور الوسطى"))
        self.textEdit_8.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Traditional Arabic\'; font-size:14pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400;\"><br /></p></body></html>"))
        self.textEdit_9.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Traditional Arabic\'; font-size:14pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400;\"><br /></p></body></html>"))
        self.textEdit_10.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Traditional Arabic\'; font-size:14pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400;\"><br /></p></body></html>"))
        self.label_17.setText(_translate("MainWindow", "مثال العصر الحديث  "))
        self.label_18.setText(_translate("MainWindow", "مثال القرآن الكريم"))
        self.pushButton4.setText(_translate("MainWindow", "أكثر"))
        self.label_34.setText(_translate("MainWindow", "إختيار الكلمة"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "الوضع اليدوي "))
        self.comboBox.setItemText(0, _translate("MainWindow", "العصر الجاهلي"))
        self.comboBox.setItemText(1, _translate("MainWindow", "عصر فجر الإسلام"))
        self.comboBox.setItemText(2, _translate("MainWindow", "العصر الأموي"))
        self.comboBox.setItemText(3, _translate("MainWindow", "العصر العباسي"))
        self.comboBox.setItemText(4, _translate("MainWindow", "العصور الوسطى"))
        self.comboBox.setItemText(5, _translate("MainWindow", "العصر الحديث"))
        self.comboBox.setItemText(6, _translate("MainWindow", "القرآن الكريم"))
        item = self.tableWidget_Corpus.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "0"))
        item = self.tableWidget_Corpus.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "المؤلفات و المؤلفون"))
        __sortingEnabled = self.tableWidget_Corpus.isSortingEnabled()
        self.tableWidget_Corpus.setSortingEnabled(False)
        self.tableWidget_Corpus.setSortingEnabled(__sortingEnabled)
        self.textEdit_16.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Traditional Arabic\'; font-size:14pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400;\"><br /></p></body></html>"))
        self.pushButton_show.setText(_translate("MainWindow", "إظهار"))
        self.label_22.setText(_translate("MainWindow", "النص المختار"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "النصوص "))
        self.groupBox.setTitle(_translate("MainWindow", "مقارنة الإختلاف  "))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "العصر الجاهلي"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "عصر فجر الإسلام"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "العصر الأموي"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "العصر العباسي"))
        self.comboBox_2.setItemText(4, _translate("MainWindow", "العصور الوسطى"))
        self.comboBox_2.setItemText(5, _translate("MainWindow", "العصر الحديث"))
        self.comboBox_2.setItemText(6, _translate("MainWindow", "القرآن الكريم"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "العصر الجاهلي"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "عصر فجر الإسلام"))
        self.comboBox_3.setItemText(2, _translate("MainWindow", "العصر الأموي"))
        self.comboBox_3.setItemText(3, _translate("MainWindow", "العصر العباسي"))
        self.comboBox_3.setItemText(4, _translate("MainWindow", "العصور الوسطى"))
        self.comboBox_3.setItemText(5, _translate("MainWindow", "العصر الحديث"))
        self.comboBox_3.setItemText(6, _translate("MainWindow", "القرآن الكريم"))
        self.pushButton_2.setText(_translate("MainWindow", "مقارنة"))
        self.label_23.setText(_translate("MainWindow", "العصر 1  "))
        self.label_24.setText(_translate("MainWindow", "العصر 2"))
        self.groupBox_2.setTitle(_translate("MainWindow", "الكلمات الأكثر شيوعا"))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "العصر الجاهلي"))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "عصر فجر الإسلام"))
        self.comboBox_4.setItemText(2, _translate("MainWindow", "العصر الأموي"))
        self.comboBox_4.setItemText(3, _translate("MainWindow", "العصر العباسي"))
        self.comboBox_4.setItemText(4, _translate("MainWindow", "العصور الوسطى"))
        self.comboBox_4.setItemText(5, _translate("MainWindow", "العصر الحديث"))
        self.comboBox_4.setItemText(6, _translate("MainWindow", "القرآن الكريم"))
        self.label_25.setText(_translate("MainWindow", "العصر"))
        self.label_26.setText(_translate("MainWindow", "عدد الكلمات"))
        self.pushButton_4.setText(_translate("MainWindow", "الحصول على الكلمات"))
        self.groupBox_3.setTitle(_translate("MainWindow", " إحصائيات النصوص  "))
        self.pushButton_5.setText(_translate("MainWindow", "إختيار النص"))
        self.label_27.setText(_translate("MainWindow", "متوسط طول الكلمات"))
        self.label_28.setText(_translate("MainWindow", "التوزيع المتكرر للكلمات"))
        self.pushButton_6.setText(_translate("MainWindow", "الحصول على متوسط الطول "))
        self.pushButton_7.setText(_translate("MainWindow", "الحصول على التوزيع"))
        self.label_31.setText(_translate("MainWindow", "أزواج الكلمات الأكثر شيوعا"))
        self.pushButton_9.setText(_translate("MainWindow", "الحصول على أزواج الكلمات"))
        self.label_32.setText(_translate("MainWindow", "عدد الكلمات"))
        self.label_33.setText(_translate("MainWindow", "عدد الأزواج"))
        self.groupBox_4.setTitle(_translate("MainWindow", "تردد الكلمات في العصور"))
        self.comboBox_5.setItemText(0, _translate("MainWindow", "العصر الجاهلي"))
        self.comboBox_5.setItemText(1, _translate("MainWindow", "عصر فجر الإسلام"))
        self.comboBox_5.setItemText(2, _translate("MainWindow", "العصر الأموي"))
        self.comboBox_5.setItemText(3, _translate("MainWindow", "العصر العباسي"))
        self.comboBox_5.setItemText(4, _translate("MainWindow", "العصور الوسطى"))
        self.comboBox_5.setItemText(5, _translate("MainWindow", "العصر الحديث"))
        self.comboBox_5.setItemText(6, _translate("MainWindow", "القرآن الكريم"))
        self.label_29.setText(_translate("MainWindow", "العصر"))
        self.label_30.setText(_translate("MainWindow", "الكلمة"))
        self.pushButton_8.setText(_translate("MainWindow", "التردد"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "إحصائيات "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

